services:
  postgres:
    container_name: spring_sec_auth
    image: postgres:17.5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgress
      POSTGRES_DB: spring_app_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:

