spring:
  debug: true
  config:
    import: optional:classpath:.env
  application:
    name: auth-security
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  messages:
    encoding: UTF-8
    use-code-as-default-message: true

  server:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true


  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 4b738fcc00e026
    password: 3f45e8e541bc5b
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  lang:
    default-locale: en
    cache-seconds: 3600
    debug: false
    supported-languages:
      - en
      - ar

  security:
    jwt:
      private-key: ${APP_SECURITY_JWT_PRIVATE_KEY_PATH}
      public-key: ${APP_SECURITY_JWT_PUBLIC_KEY_PATH}
      access-token-expiration:  86400000       # 24h for local testing, recommended for production -> 900000 (15 min)
      refresh-token-expiration: 604800000    # 7 days

    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail